/*
 * Copyright 2020-2024 Open Networking Foundation (ONF) and the ONF Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Package events Common Logger initialization
package events

import (
	"context"
	"time"

	"github.com/opencord/voltha-lib-go/v7/pkg/events/eventif"
	"github.com/opencord/voltha-lib-go/v7/pkg/log"
	"github.com/opencord/voltha-protos/v5/go/voltha"
)

// FailureErrorCode is a typed string alias for structured failure error codes
// carried in DeviceEvent.Context["error-code"].
type FailureErrorCode string

const (
	ErrCodeActivateOnu             FailureErrorCode = "ERR_ACTIVATE_ONU"
	ErrCodeOnuStateUpdateAtAdapter FailureErrorCode = "ERR_ONU_STATE_UPDATE_AT_ADAPTER"
	ErrCodeCoreUnavailable         FailureErrorCode = "ERR_CORE_UNAVAILABLE"
	ErrCodeDeviceStateUpdateAtCore FailureErrorCode = "ERR_DEVICE_STATE_UPDATE_AT_CORE"
	ErrCodeDeviceDbKvStoreUpdate   FailureErrorCode = "ERR_DEVICE_DB_KV_STORE_UPDATE"
)
const (
	//Events
	DeviceStateUpdateFailedEvent    = "OLT_DEVICE_STATE_UPDATE_FAILED"
	DeviceDBUpdateFailureEvent      = "OLT_DEVICE_DB_UPDATE_FAILURE"
	OnuUpdateCommunicationFailEvent = "ONU_UPDATE_COMMUNICATION_FAILED"
)
const (
	// ContextOltAdminState is for the admin state of the Olt in the context of the event
	ContextOltAdminState = "admin-state"
	// ContextOltConnectState is for the connect state of the Olt in the context of the event
	ContextOltConnectState = "connect-state"
	// ContextFailureReason is to report the reason of an operation failure in the Olt
	ContextFailureReason = "failure-reason"
	// ContextOltOperState is for the operational state of the Olt in the context of the event
	ContextOltOperState = "oper-state"
	// ContextOltVendor is for the Olt vendor in the context of the event
	ContextOltVendor = "vendor"
	// ContextOltType is for the Olt type in the context of the event
	ContextOltType = "type"
	// ContextOltParentID is for the Olt parent id in the context of the event
	ContextOltParentID = "parent-id"
	// ContextOltParentPortNo is for the Olt parent port no in the context of the event
	ContextOltParentPortNo = "parent-port-no"
	// ContextOltFirmwareVersion is for the Olt firmware version in the context of the event
	ContextOltFirmwareVersion = "firmware-version"
	// ContextOltHardwareVersion is for the Olt hardware version in the context of the event
	ContextOltHardwareVersion = "hardware-version"
	// ContextOltSerialNumber is for the serial number of the OLT
	ContextOltSerialNumber = "serial-number"
	// ContextOltMacAddress is for the OLT mac address
	ContextOltMacAddress = "mac-address"
	// ContextDeviceID is for the device id in the context of the event
	ContextDeviceID = "id"
	// ContextOnuOnuID is for the Onu Id in the context of the event
	ContextOnuOnuID = "onu-id"
	// ContextOnuPonIntfID is for the PON interface Id on which the Onu Event occurred
	ContextOnuPonIntfID = "intf-id"
	// ContextOnuSerialNumber is for the serial number of the ONU
	ContextOnuSerialNumber = "serial-number"
	// ContextOnuSerialNumber is for the serial number of the ONU
	ContextOnuSerialNumber2 = "onu-serial-number"
	// ContextOnuDeviceID is for the device id of the ONU generated by VOLTHA
	ContextOnuDeviceID = "onu-device-id"
	// ContextOltDeviceID is for the device id of the OLT generated by VOLTHA
	ContextOltDeviceID = "olt-device-id"
	// ContextOltPonIntfID is for the PON interface Id on an OLT event
	ContextOltPonIntfID = "intf-id"
	// ContextOnuDrift is for the drift of an ONU in the context of an event
	ContextOnuDrift = "drift"
	// ContextOnuNewEqd is for the New Eqd of an ONU in the context of an event
	ContextOnuNewEqd = "new-eqd"
	// ContextOnuInverseBitErrorRate is for the inverse bit error rate in the context of an ONU event
	ContextOnuInverseBitErrorRate = "inverse-bit-error-rate"
	// ContextOltPonIntfOperState is for the operational state of a PON port in the context of an OLT event
	ContextOltPonIntfOperState = "oper-state"
	// ContextOnuRemoteDefectIndicatorCount is for the rdi in the context of an ONU event
	ContextOnuRemoteDefectIndicatorCount = "rdi-count"
	// ContextOnuDelineationErrors is for the delineation errors if present in an ONU events context
	ContextOnuDelineationErrors = "delineation-errors"
	// ContextOnuDifferentialDistance is for the differential distance in an ONU event context
	ContextOnuDifferentialDistance = "differential-distance"
	// ContextOltPonTechnology is to indicate the pon-technology type, ie, 'GPON' or 'XGS-PON' (TODO check for combo?)
	ContextOltPonTechnology = "pon-technology"
	// ContextOltPortLabel is to indicate the string label of the pon-port, example: pon-0
	ContextOltPortLabel = "port-label"
	// ContextErrorCode is for the error code in the context of an event
	ContextErrorCode = "error-code"
)

var logger log.CLogger

func init() {
	// Setup this package so that it's log level can be modified at run time
	var err error
	logger, err = log.RegisterPackage(log.JSON, log.ErrorLevel, log.Fields{})
	if err != nil {
		panic(err)
	}
}

func FailureEvent(event eventif.EventProxy, eventName string, contextMap map[string]string, deviceID string, raisedTs int64) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if event == nil {
		logger.Errorw(ctx, "failed-to-send--failure-event-to-kafka, eventproxy is nil", log.Fields{"ctxmap": contextMap, "device-id": deviceID})
		return
	}
	var de voltha.DeviceEvent
	/* Populating device event body */
	de.Context = contextMap
	de.ResourceId = deviceID
	de.DeviceEventName = eventName
	/* Send event to KAFKA */
	if err := event.SendDeviceEventWithKey(ctx, &de, voltha.EventCategory_EQUIPMENT, voltha.EventSubCategory_PON, raisedTs, deviceID); err != nil {
		logger.Errorw(ctx, "failed-to-send--failure-event-to-kafka", log.Fields{"ctxmap": contextMap, "error": err, "device-id": deviceID})
	}
}
